### ISSUE TITLE
Could you clarify what spatial resolution and range mean?

### ISSUE THREAD

**Issue by ginacode** [gperonato/getHorizon#1]
First off, thanks for this great program.

I am currently working with images where I am given a camera latitude, longitude, heading, and horizontal field of view. 

This script takes in a latitude, longitude, angular resolution, spatial resolution, and range.
It outputs, at the given latitude and longitude, an azimuth, elevation angle, elevation, and distance.

I figure that azimuth is the same thing as a camera heading, and a range of azimuthal angles can be described by a heading + field of view. At each azimuth, I get the elevation of the skyline at a certain distance. (Is this correct?)

But what does the elevation angle mean? And what would the spatial resolution and range inputs refer to in this case?

**Comment by gperonato** [comment]
Hi,
I am happy that are you using this tool. I understand that the naming of the variables is not that straightforward. You are right about the heading and the elevation of the skyline. The elevation angle is the the angle between the [horizontal plane and the line of sight](https://www.mathsteacher.com.au/year10/ch15_trigonometry/12_elevation_depression/Image5676.gif) .
The spatial resolution _dstep_ refers to the sampling resolution that is used to calculate the skyline. The script is querying the online API for the elevation of points: for every azimuth angle _astep_ (10° if you set the angular resolution to 10), it will look for the elevation of every point at a _dstep_ distance from the viewpoint up to a maximum distance _dmax_ called _range_.
I would suggest to load the *.CSV output in GoogleEarth so you can visualize the skyline on a map and check whether the parameters are correct for your use. You can also have a look at another online tool ([synby.com](https://www.synby.com)) based on getHorizon that provides you with the same output.
Let me know if you need further help.
Giuseppe
